sudo: false
language: php
os:
  - linux
php:
  - 7.4
  - nightly
before_script:
  - composer self-update
  - composer install --prefer-dist
script: composer run-script test
notifications:
  email: false
